---

- name: Setup local environment
  hosts: 127.0.0.1
  connection: local
  gather_facts: yes

  roles:
    - role: fonts
      tags: fonts
    - role: terminal
      tags: terminal
    - role: wp
      tags: wp
    - role: wm
      tags: wm
    - role: neovim
      tags: neovim
        #- role: prompt
        # tags: prompt
    - role: geerlingguy.nodejs
      become: yes
      tags: nodejs
      # todo: sudo npm config set cache $HOME/.cache/npm --global
    - role: golang
      tags: golang
    - role: git
      tags: git

  tasks:
    - name: Ensure apt is up to date
      become: true
      apt:
        update_cache: yes
        upgrade: yes
    - name: Ensure some simple tools are installed on on the latest version
      become: true
      apt:
        name:
          - jq
          - neofetch
        state: latest

    # Disable asking for sudo password
    - name: Ensure asking for sudo password is disable
      become: true
      lineinfile:
        path: /etc/sudoers
        regexp: "^{{ lookup('env', 'USER') }}"
        line: "{{ lookup('env', 'USER') }} ALL=(ALL) NOPASSWD: ALL"

    # - name: Update .barhrc
      # blockinfile:
        # path: /home/pawilonek/.bashrc
        # marker: "## {mark} [ansible] k8s"
        # block: |
          # alias k="kubectl"

    # kubectx

    # - name: Get stuff from git
      # git:
        # repo: https://github.com/ahmetb/kubectx.git
        # dest: /opt/kubectx
    # - name: Create symbolic link
      # file:
        # src: /opt/kubectx/kubectx
        # dest: /usr/local/bin/kubectx
        # state: link
    # - name: Create symbolic link
      # file:
        # src: /opt/kubectx/kubens
        # dest: /usr/local/bin/kubens
        # state: link

      # kubeseal
      # https://github.com/bitnami-labs/sealed-secrets/releases


    # php 7.4

    # - name: Ensure php is installed
      # apt_repository:
        # repo: ppa:ondrej/php
        # state: present
    # - apt:
        # name:
          # - php7.4-fpm
          # - php7.4-xml
        # update_cache: yes
        # state: present

  # Install composer :>
  # https://getcomposer.org/download/


    - name: Install FZF
      become: yes
      apt:
        name:
          - fzf
        state: present
    # todo: move it to roles
    # - name: Get stuff from git
      # git:
        # repo: https://github.com/junegunn/fzf.git
        # dest: /opt/fzf
    # RUN: /opt/fzf/install
    # - name: Update .barhrc
      # blockinfile:
        # path: /home/pawilonek/.bashrc
        # marker: "## {mark} [ansible] fzf"
        # Auto generated
        # [ -f ~/.fzf.bash ] && source ~/.fzf.bash
        # block: |
          # export PATH=$PATH:/opt/fzf/bin
          # [[ $- == *i* ]] && source "/opt/fzf/shell/completion.bash" 2> /dev/null/

