---

- name: Ensure nvim stabile repository is present
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/unstable
    state: present

- name: Ensure nvim is installed in the latest version
  become: true
  apt:
    update_cache: yes
    name:
     - neovim
    state: latest
 
- name: Ensures nvim configuration direcotry exist
  file:
    path: ~/.config/nvim
    state: directory

- name: Copy nvim configuration files
  copy:
    src: nvim
    dest:  ~/.config
  notify: Install nvim plugins

- name: Update .barhrc
  blockinfile:
    path: ~/.bashrc
    marker: "## {mark} [ansible] nvim config"
    block: |
        alias vim="nvim"
        alias vi="nvim"
        alias v="nvim"
        export EDITOR=nvim

# Completion for neovim
- include: coc.yml

