---

- name: Ensure feh is installed in the latest version
  become: true
  apt:
    update_cache: yes
    name:
     - feh
    state: latest
 
- name: Ensure wallpaper is copied
  copy:
    src: wp.png
    dest:  ~/.config/wp.png

